{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 1,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  '1': 
   { type: 'tag',
     name: 'table',
     attribs: { class: 'infobox', style: 'float:right; width:16em' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 2,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  '1': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox',
        cellspacing: '3',
        style: 'border-spacing:3px;width:22em;border-collapse: collapse; border-spacing: 0px; border:none; width:100%; margin:0px; font-size: 100%; clear:none; float:none;;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: null,
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: null,
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  '2': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox',
        cellspacing: '3',
        style: 'border-spacing:3px;width:22em;border-collapse: collapse; border-spacing: 0px; border:none; width:100%; margin:0px; font-size: 100%; clear:none; float:none;;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: null,
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: null,
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  '3': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox',
        cellspacing: '3',
        style: 'border-spacing:3px;width:22em;border-collapse: collapse; border-spacing: 0px; border:none; width:100%; margin:0px; font-size: 100%; clear:none; float:none;;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: null,
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: null,
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 4,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 1,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 1,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox geography vcard',
        style: 'width:22em; font-size:88%;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 1,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
{ '0': 
   { type: 'tag',
     name: 'table',
     attribs: 
      { class: 'infobox',
        cellspacing: '3',
        style: 'border-spacing:3px;width:22em;' },
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: [Object],
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object],
        data: {} },
     data: {} },
  length: 1,
  prevObject: 
   { '0': 
      { type: 'root',
        name: 'root',
        parent: null,
        prev: null,
        next: null,
        children: [Object] },
     length: 1,
     _root: [Circular] } }
